name: release

on:
  push:
    branches:
      - 'release/**'

jobs:
  publish:
    name: Release Recompose Library
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Gradle and wrapper
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant Permission for Gradlew to Execute
        run: chmod +x gradlew

      - name: Build AAR ⚙️🛠
        run: ./gradlew :recompose:assemble

      - name: Publish to Maven Central 🚀
        run: ./gradlew :recompose:publishReleasePublicationToDeployRepository
        env:
          RELEASE_VERSION: ${{ github.ref }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}

      - name: Create Release ✅
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false

      - name: Upload Re-compose Library AAR 🗳
        uses: softprops/action-gh-release@v1
        with:
          files: recompose/build/outputs/aar/recompose-release.aar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}